package claudecookie

import (
	"errors"
	"strings"
	"testing"
	"time"
)

// reference is the shape Cookie-Editor produces for a claude.ai export: a
// Netscape header, an #HttpOnly_ prefixed line, tab separated fields, and both
// sessionKey and sessionKeyV3 present.
const netscapeExport = "# Netscape HTTP Cookie File\n" +
	"# http://curl.haxx.se/rfc/cookie_spec.html\n" +
	"# This file was generated by Cookie-Editor\n" +
	"#HttpOnly_.claude.ai\tTRUE\t/\tTRUE\t4000000000\t__cf_bm\tcfvalue\n" +
	"claude.ai\tFALSE\t/\tTRUE\t4000000000\tanthropic-device-id\tdev-1\n" +
	".claude.ai\tTRUE\t/\tTRUE\t4000000000\tsessionKey\tsk-ant-sid02-primary\n" +
	".claude.ai\tTRUE\t/\tTRUE\t4000000000\tsessionKeyV3\tsk-ant-sid02-v3\n" +
	".claude.ai\tTRUE\t/\tTRUE\t4000000000\tlastActiveOrg\torg-1\n"

func TestParseOneNetscape(t *testing.T) {
	got, err := ParseOne(netscapeExport)
	if err != nil {
		t.Fatalf("ParseOne() error = %v", err)
	}

	if got.SessionKey != "sk-ant-sid02-primary" {
		t.Errorf("SessionKey = %q, want the sessionKey cookie value", got.SessionKey)
	}
	if len(got.Names) != 5 {
		t.Errorf("Names = %v, want 5 cookies", got.Names)
	}
	// The jar must be a sendable Cookie header preserving file order.
	wantJar := "__cf_bm=cfvalue; anthropic-device-id=dev-1; sessionKey=sk-ant-sid02-primary; " +
		"sessionKeyV3=sk-ant-sid02-v3; lastActiveOrg=org-1"
	if got.Jar != wantJar {
		t.Errorf("Jar =\n  %q\nwant\n  %q", got.Jar, wantJar)
	}
}

func TestParseOneNetscapeDropsExpiredCookies(t *testing.T) {
	// __cf_bm is short lived; a browser would not replay an expired one.
	raw := "#HttpOnly_.claude.ai\tTRUE\t/\tTRUE\t1000000000\t__cf_bm\tstale\n" +
		".claude.ai\tTRUE\t/\tTRUE\t4000000000\tsessionKey\tsk-ant-sid02-fresh\n"

	got, err := ParseOne(raw)
	if err != nil {
		t.Fatalf("ParseOne() error = %v", err)
	}
	if strings.Contains(got.Jar, "__cf_bm") {
		t.Errorf("Jar = %q, want expired __cf_bm dropped", got.Jar)
	}
	if got.SessionKey != "sk-ant-sid02-fresh" {
		t.Errorf("SessionKey = %q", got.SessionKey)
	}
}

func TestParseOneNetscapeKeepsSessionCookies(t *testing.T) {
	// expiry 0 means a session cookie, not an expired one.
	raw := ".claude.ai\tTRUE\t/\tTRUE\t0\ttransient\tkeep\n" +
		".claude.ai\tTRUE\t/\tTRUE\t4000000000\tsessionKey\tsk-ant-sid02-x\n"

	got, err := ParseOne(raw)
	if err != nil {
		t.Fatalf("ParseOne() error = %v", err)
	}
	if !strings.Contains(got.Jar, "transient=keep") {
		t.Errorf("Jar = %q, want session cookie kept", got.Jar)
	}
}

func TestParseOneJSONArray(t *testing.T) {
	raw := `[
	  {"name":"anthropic-device-id","value":"dev-1","domain":".claude.ai"},
	  {"name":"sessionKey","value":"sk-ant-sid02-json","domain":".claude.ai","expirationDate":4000000000}
	]`

	got, err := ParseOne(raw)
	if err != nil {
		t.Fatalf("ParseOne() error = %v", err)
	}
	if got.SessionKey != "sk-ant-sid02-json" {
		t.Errorf("SessionKey = %q", got.SessionKey)
	}
	if got.Jar != "anthropic-device-id=dev-1; sessionKey=sk-ant-sid02-json" {
		t.Errorf("Jar = %q", got.Jar)
	}
}

func TestParseOneJSONObjectMap(t *testing.T) {
	raw := `{"sessionKey":"sk-ant-sid02-map","lastActiveOrg":"org-9"}`

	got, err := ParseOne(raw)
	if err != nil {
		t.Fatalf("ParseOne() error = %v", err)
	}
	if got.SessionKey != "sk-ant-sid02-map" {
		t.Errorf("SessionKey = %q", got.SessionKey)
	}
	if !strings.Contains(got.Jar, "sessionKey=sk-ant-sid02-map") ||
		!strings.Contains(got.Jar, "lastActiveOrg=org-9") {
		t.Errorf("Jar = %q, want both cookies", got.Jar)
	}
}

func TestParseOneCookieHeader(t *testing.T) {
	raw := "  anthropic-device-id=dev-1; sessionKey=sk-ant-sid02-hdr; lastActiveOrg=org-2  "

	got, err := ParseOne(raw)
	if err != nil {
		t.Fatalf("ParseOne() error = %v", err)
	}
	if got.SessionKey != "sk-ant-sid02-hdr" {
		t.Errorf("SessionKey = %q", got.SessionKey)
	}
	if got.Jar != "anthropic-device-id=dev-1; sessionKey=sk-ant-sid02-hdr; lastActiveOrg=org-2" {
		t.Errorf("Jar = %q", got.Jar)
	}
}

func TestParseOneBareSessionKey(t *testing.T) {
	got, err := ParseOne("  sk-ant-sid02-bare  ")
	if err != nil {
		t.Fatalf("ParseOne() error = %v", err)
	}
	if got.SessionKey != "sk-ant-sid02-bare" {
		t.Errorf("SessionKey = %q", got.SessionKey)
	}
	if got.Jar != "sessionKey=sk-ant-sid02-bare" {
		t.Errorf("Jar = %q, want a synthesised jar", got.Jar)
	}
}

func TestParseOneSingleKeyValuePair(t *testing.T) {
	// A one-cookie paste with no trailing semicolon.
	got, err := ParseOne("sessionKey=sk-ant-sid02-pair")
	if err != nil {
		t.Fatalf("ParseOne() error = %v", err)
	}
	if got.SessionKey != "sk-ant-sid02-pair" {
		t.Errorf("SessionKey = %q", got.SessionKey)
	}
}

func TestParseOneFallsBackToSessionKeyV3(t *testing.T) {
	raw := ".claude.ai\tTRUE\t/\tTRUE\t4000000000\tsessionKeyV3\tsk-ant-sid02-only-v3\n"

	got, err := ParseOne(raw)
	if err != nil {
		t.Fatalf("ParseOne() error = %v", err)
	}
	if got.SessionKey != "sk-ant-sid02-only-v3" {
		t.Errorf("SessionKey = %q, want the sessionKeyV3 fallback", got.SessionKey)
	}
}

func TestParseOneErrors(t *testing.T) {
	tests := []struct {
		name string
		raw  string
	}{
		{"empty", "   \n  \n"},
		{"comments only", "# Netscape HTTP Cookie File\n# nothing else\n"},
		{"no session key", "anthropic-device-id=dev-1; lastActiveOrg=org-2"},
		{"netscape without session key", ".claude.ai\tTRUE\t/\tTRUE\t4000000000\tARID\tvalue\n"},
		{"malformed json", "[{\"name\":}]"},
		{"garbage", "hello world this is not a cookie"},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			if _, err := ParseOne(tc.raw); !errors.Is(err, ErrNoSessionKey) {
				t.Errorf("ParseOne() error = %v, want ErrNoSessionKey", err)
			}
		})
	}
}

func TestParseManyBatchOfBareKeys(t *testing.T) {
	raw := "sk-ant-sid02-a\n\n  sk-ant-sid02-b  \nsk-ant-sid02-c\n"

	got, err := ParseMany(raw)
	if err != nil {
		t.Fatalf("ParseMany() error = %v", err)
	}
	if len(got) != 3 {
		t.Fatalf("len = %d, want 3 accounts", len(got))
	}
	for i, want := range []string{"sk-ant-sid02-a", "sk-ant-sid02-b", "sk-ant-sid02-c"} {
		if got[i].SessionKey != want {
			t.Errorf("[%d].SessionKey = %q, want %q", i, got[i].SessionKey, want)
		}
		if got[i].Jar != "sessionKey="+want {
			t.Errorf("[%d].Jar = %q", i, got[i].Jar)
		}
	}
}

func TestParseManyTreatsNetscapeAsOneAccount(t *testing.T) {
	// A multi-line Netscape export must not be mistaken for a batch of keys.
	got, err := ParseMany(netscapeExport)
	if err != nil {
		t.Fatalf("ParseMany() error = %v", err)
	}
	if len(got) != 1 {
		t.Fatalf("len = %d, want 1 account", len(got))
	}
	if got[0].SessionKey != "sk-ant-sid02-primary" {
		t.Errorf("SessionKey = %q", got[0].SessionKey)
	}
	if !strings.Contains(got[0].Jar, "lastActiveOrg=org-1") {
		t.Errorf("Jar = %q, want full jar preserved", got[0].Jar)
	}
}

func TestParseManyTreatsJSONAsOneAccount(t *testing.T) {
	raw := `[{"name":"sessionKey","value":"sk-ant-sid02-j"},
	{"name":"lastActiveOrg","value":"org-3"}]`

	got, err := ParseMany(raw)
	if err != nil {
		t.Fatalf("ParseMany() error = %v", err)
	}
	if len(got) != 1 {
		t.Fatalf("len = %d, want 1 account", len(got))
	}
}

func TestParseManyRejectsBatchWhenALineHasNoSessionKey(t *testing.T) {
	raw := "sk-ant-sid02-a\nnot-a-session-key\n"
	if _, err := ParseMany(raw); !errors.Is(err, ErrNoSessionKey) {
		t.Errorf("ParseMany() error = %v, want ErrNoSessionKey", err)
	}
}

func TestJarForSessionKey(t *testing.T) {
	if got := JarForSessionKey("sk-ant-sid02-z"); got != "sessionKey=sk-ant-sid02-z" {
		t.Errorf("JarForSessionKey() = %q", got)
	}
	if got := JarForSessionKey(""); got != "" {
		t.Errorf("JarForSessionKey(\"\") = %q, want empty", got)
	}
}

func TestParseOneIgnoresShortNetscapeLines(t *testing.T) {
	// Wrapped/truncated lines must not corrupt the jar.
	raw := ".claude.ai\tTRUE\t/\n" +
		".claude.ai\tTRUE\t/\tTRUE\t4000000000\tsessionKey\tsk-ant-sid02-ok\n"

	got, err := ParseOne(raw)
	if err != nil {
		t.Fatalf("ParseOne() error = %v", err)
	}
	if got.Jar != "sessionKey=sk-ant-sid02-ok" {
		t.Errorf("Jar = %q", got.Jar)
	}
}

func TestParseOneNetscapeWithSpaceSeparatedFields(t *testing.T) {
	// Some editors mangle tabs into runs of spaces on copy/paste.
	raw := ".claude.ai TRUE / TRUE 4000000000 sessionKey sk-ant-sid02-spaced"

	got, err := ParseOne(raw)
	if err != nil {
		t.Fatalf("ParseOne() error = %v", err)
	}
	if got.SessionKey != "sk-ant-sid02-spaced" {
		t.Errorf("SessionKey = %q", got.SessionKey)
	}
}

func TestParseAtClockBoundary(t *testing.T) {
	now := time.Unix(2_000_000_000, 0)
	raw := ".claude.ai\tTRUE\t/\tTRUE\t1999999999\told\tv1\n" +
		".claude.ai\tTRUE\t/\tTRUE\t2000000001\tsessionKey\tsk-ant-sid02-b\n"

	got, err := parseOneAt(raw, now)
	if err != nil {
		t.Fatalf("parseOneAt() error = %v", err)
	}
	if strings.Contains(got.Jar, "old=v1") {
		t.Errorf("Jar = %q, want cookie expiring before now dropped", got.Jar)
	}
}
